// lists of available things from each category to be picked from
export let weaponsList = [  
    {
        name: "Advanced Zweihander",
        grade: 5,
        damageType: "Slash",
        damageAmount: 9,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Butler's Briefcase",
        grade: 4,
        damageType: "Slash",
        damageAmount: 5,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 8,
        rangeHeight: 7
    },
    {
        name: "Blade Lineage Hwando",
        grade: 5,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Bloodfiend Claws",
        grade: 0,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.44,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 6,
        rangeHeight: 7
    },
    {
        name: "Blade Lineage Jikdo",
        grade: 1,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Backstreet Chef's Knife",
        grade: 0,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.46,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 6,
        rangeHeight: 7
    },
    {
        name: "Crystal Atelier",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Dagger",
        grade: 0,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.46,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 6,
        rangeHeight: 7
    },
    {
        name: "Durandal",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.71,
        hitStartup: null,
        rangeLength: 12.5,
        rangeWidth: 6,
        rangeHeight: 9.5
    },
    {
        name: "Fixer's Shortsword",
        grade: 0,
        damageType: "Slash",
        damageAmount: 5.5,
        swingDelay: 0.37,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 9
    },
    {
        name: "Fixer's Battleaxe",
        grade: 0,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.68,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Fixer's Blade",
        grade: 0,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.48,
        hitStartup: 0.33, // Este foi o que você forneceu
        rangeLength: 9,
        rangeWidth: 6,
        rangeHeight: 9.5
    },
    {
        name: "Fused Blade of Ruined Mirror Worlds",
        grade: 1,
        damageType: "Slash",
        damageAmount: 10,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Family Heir's Sabre",
        grade: 4,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.63,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 4,
        rangeHeight: 10
    },
    {
        name: "Hardblood Blade",
        grade: 0,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Hardblood Greatblade",
        grade: 1,
        damageType: "Slash",
        damageAmount: 9,
        swingDelay: 0.73,
        hitStartup: null,
        rangeLength: 10.5,
        rangeWidth: 7,
        rangeHeight: 10.5
    },
    {
        name: "Hardblood Claws",
        grade: 0,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 6,
        rangeHeight: 7
    },
    {
        name: "Hardblood Scissorblades",
        grade: 5,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Great Hardblood Scissorblades",
        grade: 2,
        damageType: "Slash",
        damageAmount: 9,
        swingDelay: 0.67,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 13
    },
    {
        name: "Hardblood Polearm",
        grade: 4,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Hardblood Whip",
        grade: 2,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.65,
        hitStartup: null,
        rangeLength: 14,
        rangeWidth: 6,
        rangeHeight: 14
    },
    {
        name: "Index Greatsword",
        grade: 4,
        damageType: "Slash",
        damageAmount: 9,
        swingDelay: 0.67,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "Index Cleaver",
        grade: 4,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.73,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Kurokumo Katana",
        grade: 6,
        damageType: "Slash",
        damageAmount: 7.5,
        swingDelay: 0.69,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Kurokumo Gilded Katana",
        grade: 6,
        damageType: "Slash",
        damageAmount: 7.5,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 6,
        rangeHeight: 9.5
    },
    {
        name: "Mimicry Blade",
        grade: 1,
        damageType: "Slash",
        damageAmount: 6.5,
        swingDelay: 0.5,
        hitStartup: null,
        rangeLength: 10.5,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Mook Workshop",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.45,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Rabbit Rifle",
        grade: 5,
        damageType: "Slash",
        damageAmount: 5,
        swingDelay: 0.4,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 8.5
    },
    {
        name: "Reverberation Scythe",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.63,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "R Corp. Sabre",
        grade: 5,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 10.5,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Sharp Greatsword",
        grade: 0,
        damageType: "Slash",
        damageAmount: 9.4,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Soldato Rifle",
        grade: 6,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Sweeper Hooks",
        grade: 0,
        damageType: "Slash",
        damageAmount: 5.5,
        swingDelay: 0.42,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 6,
        rangeHeight: 8
    },
    {
        name: "Seven Association Longsword",
        grade: 7,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.69,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Stigma Workshop Sword",
        grade: 4,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.61,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 6,
        rangeHeight: 9
    },
    {
        name: "Shi Association Katana",
        grade: 4,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.53,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Tanglecleaver",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Twinhook",
        grade: 7,
        damageType: "Slash",
        damageAmount: 5.5,
        swingDelay: 0.4,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 8.5
    },
    {
        name: "TIMETRACK Corp. Collection Pickaxe",
        grade: 5,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 12.5,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Udjat Khopesh",
        grade: 4,
        damageType: "Slash",
        damageAmount: 6.5,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Udjat Vanguard Khopesh",
        grade: 4,
        damageType: "Slash",
        damageAmount: 5.5,
        swingDelay: 0.45,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "WARP Corp. Machetes",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "WARP Corp. Odachi",
        grade: 3,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.44,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Zweihander",
        grade: 6,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "Index Longsword",
        grade: 1,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Scythe of Mimicry",
        grade: 3,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Palermitian Style Blades",
        grade: 1,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Superthermogenesis Gladius",
        grade: 1,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 7
    },
    {
        name: "Moonlit Azure Blade",
        grade: 1,
        damageType: "Slash",
        damageAmount: 5,
        swingDelay: 0.48,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Farmwatch Scythe",
        grade: 3,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.69,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "4th Match Blade",
        grade: 3,
        damageType: "Slash",
        damageAmount: 7,
        swingDelay: 0.68,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Ebony Stem Cutlass",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6.5,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Flaring Brand",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6.5,
        swingDelay: 0.63,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Nine Children of the Dragon Guan Dao",
        grade: 3,
        damageType: "Slash",
        damageAmount: 9,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Red Eyes Blade",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6.5,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Sanguine Desire Axe",
        grade: 3,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "Rough Axe",
        grade: 5,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Fascia (Sealed)",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 12.5,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Crimson Scar Carver",
        grade: 3,
        damageType: "Slash",
        damageAmount: 5.5,
        swingDelay: 0.65,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 8.5
    },
    {
        name: "Thermal Blade Weaponry",
        grade: 3,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 8
    },
{
        name: "Iron Brotherhood Saw",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 8.25,
        swingDelay: 0.63,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 6,
        rangeHeight: 11
    },
    {
        name: "Fixer's Chainsaw",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 9.9,
        swingDelay: 0.73,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 6,
        rangeHeight: 11
    },
    {
        name: "Fixer's Spear",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Fixer's Handsaw",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.42,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 6,
        rangeHeight: 9
    },
    {
        name: "Hook Cleaver",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 5,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 6,
        rangeHeight: 9
    },
    {
        name: "Scrap Spear",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 5,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Whaling Harpoon",
        grade: 8,
        damageType: "Pierce",
        damageAmount: 7,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Liu Guan Dao",
        grade: 7,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 10.5,
        rangeWidth: 6,
        rangeHeight: 10.5
    },
    {
        name: "Gasharpoon",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Pointillist Brush",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 7,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Liu Martial Arts",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.51,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 4,
        rangeHeight: 8
    },
    {
        name: "Molar Boatwork's Arm Harpoon",
        grade: 4,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "N Corp. Nail",
        grade: 2,
        damageType: "Pierce",
        damageAmount: 7,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "The Silver Bullet",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Seraphic Lance",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Cinq Rapier",
        grade: 4,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 5,
        rangeWidth: 4,
        rangeHeight: 11
    },
    {
        name: "Executioner's Polearm",
        grade: 4,
        damageType: "Pierce",
        damageAmount: 7.5,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "Explosive Spear",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.49,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Full-Stop Pistol",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 4,
        swingDelay: 0.71,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "WARP Corp. Dagger",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.37,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Augury Spear",
        grade: 2,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Eye Gouger",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 5,
        swingDelay: 0.43,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Deathseeker Nail",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 4,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Allas Workshop",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 7.5,
        swingDelay: 0.64,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Yesterday's Promise",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.42,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Ranga Workshop",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.51,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 7
    },
    {
        name: "Hardblood Parasol",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 6.5,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 6,
        rangeHeight: 11
    },
    {
        name: "Hardblood Lance",
        grade: 2,
        damageType: "Pierce",
        damageAmount: 9,
        swingDelay: 0.65,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 4,
        rangeHeight: 14
    },
    {
        name: "Hardblood Greatlance",
        grade: 2,
        damageType: "Pierce",
        damageAmount: 10,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 4,
        rangeHeight: 14
    },
    {
        name: "Executioner's Claw",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.65,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Thundering Pole",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 8,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Dimension Shredding Spear",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 7,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Roseate Desire Scissors",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 8,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Blooming Staff",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Fell Bullet Rifle",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Sunshower Umbrella",
        grade: 3,
        damageType: "Pierce",
        damageAmount: 6.5,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Solemn Lament Pistols",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 12.5
    },
    {
        name: "Viriscent Pyrojade Ring",
        grade: 6,
        damageType: "Pierce",
        damageAmount: 5,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Zweihander",
        grade: 6,
        damageType: "Slash",
        damageAmount: 8,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "Index Proxy's Shackles",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.51,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Greatsword",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 9.4,
        swingDelay: 0.64,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Flaming Bat",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.63,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Steam Gauntlet",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Scrap Bat",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Brawler",
        grade: 8,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.53,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Brutish Brawler",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.67,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Beak Bat",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 6,
        rangeHeight: 10
    },
    {
        name: "Rosespanner Hammer",
        grade: 7,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.72,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Hardblood Gauntlets",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 5.5,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 6,
        rangeHeight: 7
    },
    {
        name: "Hardblood Staff",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 8.5
    },
    {
        name: "Multicrack Charged Blades",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 10,
        swingDelay: 0.79,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Dieci Association Kata",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.74,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7
    },
    {
        name: "Chains of Loyalty",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Rosespanner Crusher",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 8,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10.5
    },
    {
        name: "N Corp. Inquisitor Hammer",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "R Corp. Hammer",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 10,
        swingDelay: 0.68,
        hitStartup: null,
        rangeLength: 15,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Smoke Staff",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 9.5
    },
    {
        name: "Full-Stop Automatic",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 5.5,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "R Corp. Staff",
        grade: 5,
        damageType: "Blunt",
        damageAmount: 8,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Dieci Association Key",
        grade: 4,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "WARP Corp. Gauntlets",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Knuckles of Discipline",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.69,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Dragon's Bite",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Zelkova Workshop",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 8,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Old Boys Workshop",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Wheel's Industry (Sword)",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 10,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Wheel's Industry (Fist)",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.7,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "L'Heure du Loup",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.56,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "The Crying Children",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.49,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Leaflet Workshop Steamgun",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 7.5,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 11.5
    },
    {
        name: "Stigma Workshop Gauntlets",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
    {
        name: "Zwei Association Greatsword",
        grade: 4,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "N Corp. Mittelhammer Hammer",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.73,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Worn Sledgehammer",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 8.5,
        swingDelay: 0.6,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Hell and Heaven",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 5.5,
        swingDelay: 0.49,
        hitStartup: null,
        rangeLength: 7,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Piston Gauntlets",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.47,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Blue Star Orb",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 5,
        swingDelay: 0.57,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Smile Hammer",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 8,
        swingDelay: 0.62,
        hitStartup: null,
        rangeLength: 9.5,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Smiling Mass",
        grade: 4,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Blind Obsession Anchor",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.79,
        hitStartup: null,
        rangeLength: 12,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Regret Hammer",
        grade: 3,
        damageType: "Blunt",
        damageAmount: 7.5,
        swingDelay: 0.67,
        hitStartup: null,
        rangeLength: 11,
        rangeWidth: 8,
        rangeHeight: 12
    },
    {
        name: "Furnace Workshop Hammer",
        grade: 4,
        damageType: "Blunt",
        damageAmount: 9,
        swingDelay: 0.78,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Magic Bullet Rifle",
        grade: 6,
        damageType: "Blunt",
        damageAmount: 6.5,
        swingDelay: 0.59,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Fluid Sac Hammer",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 8.5,
        swingDelay: 0.75,
        hitStartup: null,
        rangeLength: 13,
        rangeWidth: 8,
        rangeHeight: 11
    },
    {
        name: "Oni Tekko",
        grade: 1,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.54,
        hitStartup: null,
        rangeLength: 7.5,
        rangeWidth: 8,
        rangeHeight: 7.5
    },
    {
        name: "Lamp",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 7,
        swingDelay: 0.67,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 9
    },
    {
        name: "Executioner's Claw",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 6,
        swingDelay: 0.65,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 8,
        rangeHeight: 8
    },
{
        name: "Ebony & Ivory",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 4,
        swingDelay: 0.60,
        hitStartup: null,
        rangeLength: 4,
        rangeWidth: 4,
        rangeHeight: 11
    },
    {
        name: "Golden Ecstasy",
        grade: 0,
        damageType: "Blunt",
        damageAmount: 6,
        swingDelay: 0.50,
        hitStartup: null,
        rangeLength: 4,
        rangeWidth: 4,
        rangeHeight: 13
    },
    {
        name: "Libe & Hessen",
        grade: 0,
        damageType: "Pierce",
        damageAmount: 5,
        swingDelay: 0.55,
        hitStartup: null,
        rangeLength: 8.5,
        rangeWidth: 6,
        rangeHeight: 11
    },
    {
        name: "Leviathan Blade",
        grade: 3,
        damageType: "Slash",
        damageAmount: 8.5,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 9,
        rangeWidth: 8,
        rangeHeight: 10
    },
    {
        name: "Five-Seven & Deagle",
        grade: 1,
        damageType: "Pierce",
        damageAmount: 7,
        swingDelay: 0.58,
        hitStartup: null,
        rangeLength: 8,
        rangeWidth: 8,
        rangeHeight: 12.5
    },
    {
        name: "Dawnbreaker",
        grade: 2,
        damageType: "Slash",
        damageAmount: 6,
        swingDelay: 0.52,
        hitStartup: null,
        rangeLength: 10,
        rangeWidth: 8,
        rangeHeight: 9
    }
];

export let outfitsList = ["outfit1", "outfit2"];

export let egoList = ["ego1", "ego2"];

export let egoGiftList = ["egift1", "egift2"];

export let traits = [
    "agile", 
    "bizarre", 
    "calm", 
    "chain_dashes", 
    "hot-headed", 
    "hypoxic", 
    "immovable", 
    "indomitable", 
    "maniacal", 
    "overprepared", 
    "problem_solving", 
    "proficient", 
    "reactive", 
    "resolute", 
    "resourceful", 
    "shimmering", 
    "steadfast", 
    "time_distortion", 
    "blindspot", 
    "coldness", 
    "energetic", 
    "leeching", 
    "lunging", 
    "thrusters", 
    "methodical", 
    "paranoid", 
    "chromatic", 
    "culinary", 
    "garde", 
    "rojima"
];